name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Use LTS Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: TypeScript - check types
        run: npm run typecheck

      - name: Run tests
        run: npm test
